### ISSUE TITLE
Buscar por CIF

### ISSUE THREAD

**Issue by aesedepece** [PabloCastellano/bormeparser#99]
Más allá de por su nombre, sería conveniente poder buscar empresas por su CIF.

**Comment by PabloCastellano** [comment]
Lamentablemente en los boletines oficiales no aparecen los NIF de las empresas (anteriormente conocido como CIF)

**Comment by aesedepece** [comment]
> Lamentablemente en los boletines oficiales no aparecen los NIF de las empresas (anteriormente conocido como CIF)

Pero cuando busco el nombre de una empresa, al menos en la mayoría de casos, aparece su NIF. De modo que al menos para esas empresas sí que sería posible hacer la búsqueda inversa.

Sencillamente el otro día iba buscando información de un NIF y se me ocurrió buscarlo directamente en LibreBor sin pasar primero por Google, y me sorprendió descubrir que no era posible, pese a que esa empresa y su NIF sí que aparecían en LibreBor si la buscaba por nombre.

**Comment by PabloCastellano** [comment]
Ah! La búsqueda por NIF solo está disponible a través de la API. De todas formas este es el repositorio del parser :smiley:
